### ISSUE TITLE
Is there an executable for download yet?

### ISSUE THREAD

**Issue by molitar** [Zoltanar/Happy-Reader#1]
I been looking for a good client for searching VNDB as VNDB does not have a NOT operator and makes searching a real pain.  I found the reference to this client but could find no actual download for it yet.

**Comment by Zoltanar** [comment]
Happy Reader has NOT functionality for filters.
See the releases page:
https://github.com/Zoltanar/Happy-Reader/releases

**Comment by shoaibshakeel381** [comment]
VNDB does have NOT operator. What property are you trying to exclude Tags? Releases?

**Comment by molitar** [comment]
Actually on VNDB I figured it out.. it requires you to click on invert and that is the NOT operator.  I like to filter out the male on male there is a total of like 7 of them. male on male rape, male on male only, male on male NTR.
